redmine_db_password: "{{ vault_redmine_db_password }}"
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: datadoghq.eu
site_base_url: https://sdorodniy.site/
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Site
        url: "{{ site_base_url }}"